frontend:
  image: mujjuacr12333.azurecr.io/frontend:latest
  replicas: 1
  containerPort: 8085
  servicePort: 80

backend:
  image: mujjuacr12333.azurecr.io/backend:latest
  replicas: 1
  containerPort: 8086
  servicePort: 8086
