apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-java-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-java-backend
  template:
    metadata:
      labels:
        app: project-java-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.backend.port }}"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          ports:
            - containerPort: {{ .Values.backend.port }}
