apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-java-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-java-frontend
  template:
    metadata:
      labels:
        app: project-java-frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.frontend.port }}"
        prometheus.io/path: "/actuator/prometheus"
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image }}:{{ .Values.frontend.tag }}"
          ports:
            - containerPort: {{ .Values.frontend.port }}
